### ISSUE TITLE
RuntimeError when loading the model

### ISSUE THREAD

**Issue by oOHeavenOo** [chenmingxiang110/Growing-Neural-Cellular-Automata#2]
Hi, I was new to torch, and I have no idea what is wrong with my code. I used your Jupiter notebook to train the model. When I try to load and do the inference, an error message showed up:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

How to solve this problem?

**Comment by chenmingxiang110** [comment]
As it said, try to load the model with:

torch.load("path-to-the-model", map_location=torch.device('cpu'))
